### ISSUE TITLE
multiple-select items disappear after upgrading from slickgrid-react 3.3.2 to slickgrid-react 4.3.1

### ISSUE THREAD

**Issue by kevinburkett** [ghiscoding/multiple-select-vanilla#203]
### Describe the bug

If a large number of items are in a multiple-select drop down and you scroll too quickly, then the text of the items disappear.  The actual checkboxes are still there.  I believe it has something to do with virtual scrolling.  I was able to duplicate it on your Example 4 for React.  It seems this state is cached and the page must be reloaded to fix the issue.  It is very repeatable.  This issue did not occur on the older version of the multiple-select. 

https://ghiscoding.github.io/slickgrid-react/#/Example4

![image](https://github.com/ghiscoding/multiple-select-vanilla/assets/48218815/746246b1-995a-4e4b-b189-160ec59c7065)

### Reproduction

1. Open the link: https://ghiscoding.github.io/slickgrid-react/#/Example4
2. Select the drop down "Duration (days)"
3. Scroll the drop down quickly to the bottom and also to the top and the items disappear.  

### Expectation

It should continue to show all items no matter how long the list is.  

My drop down count that fails is approximately 2,000 items in length.

### Environment Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.97 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.6.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.85
    Safari: 17.2.1
  npmPackages:
    multiple-select-vanilla: ^1.2.4 => 1.2.4
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/multiple-select-vanilla/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/multiple-select-vanilla/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
The previous code in v0.x was using HTML string and that was bad for CSP and perf, the new approach brought in PR #146 and further advanced in PR #153 is to create native element dynamically while scrolling (instead of previously create HTML string that were sent to `.innerHTML`). The first iteration in #146 was a bit slower than before and I addressed it further in #153 I changed the structure to make it faster. 

 As far as I can see, the code works correctly in the [Large Set](https://ghiscoding.github.io/multiple-select-vanilla/#/example10) example with 10K rows and if I cannot replicate the issue in here. I don't have time at the moment to investigate further, any contributions would be more than welcome

**Comment by ghiscoding** [comment]
After doing some troubleshooting by simply toggling all the options (which you can try too), this looks to be a problem only with `useSelectOptionLabelToHtml: true`, without it then the example you referenced works fine.

**Comment by kevinburkett** [comment]
I did not have that option set.  I just tried setting that field to false and I still have the issue. I have tried it with async and without async. I have the same issue. 

Is there a way to turn off virtual scrolling? I think that might be the issue.

**Comment by ghiscoding** [comment]
I found the problem, when creating the cache for the Virtual Scroll (as referenced by the 2 PRs I mentioned earlier), I deleted the `innerHTML` property (associated to the label text) without thinking too much about the potential side effect. The side effect is that the next time the cache is revisited the `innerHTML` associated to the text label is now empty and it basically equals to no more label 

(line 99 in the code below)

https://github.com/ghiscoding/multiple-select-vanilla/blob/72ebb75d24a6a0320ffb710b76d8f66487e8bf3f/packages/multiple-select-vanilla/src/utils/domUtils.ts#L94-L100

This `innerHTML` is **only** in play when you have enabled any of the HTML rendering option, that is option can be `useSelectOptionLabelToHtml` or others, however in Slickgrid libs the option is named different as more commonly the `enableRenderHtml` which you have most probably enabled. I'm telling you, without any of the render HTML options enabled this issue does not exists.

As for the question about disabling the Virtual Scroll, it's not currently possible. That code was put in place by the original author and it's deeply integrated, I'm not interested to spend time on refactoring everything for a potential (and very rare case) of disabling the feature, the best option is really to fix the source of the problem which I have found and will push a fix in the coming days

**Comment by kevinburkett** [comment]
Thank you for the quick turnaround!  I am also rewriting my formatters so I can use the CSP implementation. I appreciate all the work you have done with these great products!

**Comment by ghiscoding** [comment]
@kevinburkett ok I pushed a new release in here v1.2.5 but I won't push releases for downstream libs like Slickgrid-React, so you'll have to use either npm override or delete your lock file then reinstall. I tried it in Slickgrid-React by deleting the lock file and the example now works correctly

![brave_haLnxY6cmh](https://github.com/ghiscoding/multiple-select-vanilla/assets/643976/fdff364e-6702-495f-92ba-14ae2a3ef830)
